### ISSUE TITLE
config and state

### ISSUE THREAD

**Issue by dali99** [dhghf/marco#11]
The bridge should load a config by default from a `config` folder by default, but also be able to take a config via a command-line argument.

The config folder makes it easier to configure it using docker volumes. The command-line argument is useful for storing config files away from the code, suitable for for example a NixOS module, or in general packaging for other distributions.

Same story goes for where the database state is stored. This should be specified in the config file.

**Comment by dhghf** [comment]
> The bridge should load a config by default from a config folder by default, but also be able to take a config via a command-line argument.

I believe the only argument I'll allow is the path to the configuration because the configuration will handle the rest.

> The config folder makes it easier to configure it using docker volumes. The command-line argument is useful for storing config files away from the code, suitable for for example a NixOS module, or in general packaging for other distributions.

Sounds good I'll add a config folder, although a DockerFile should be made once version 1 is released

> Same story goes for where the database state is stored

This will be added to the config file.
