### ISSUE TITLE
Generate avatar from offline-mode server skins

### ISSUE THREAD

**Issue by amalon** [dhghf/marco#17]
Offline mode servers can have customisable skins (e.g. with [SkinsRestorer](https://www.spigotmc.org/resources/skinsrestorer.2124/) plugin).

It'd be awesome if we could eventually transparently get the skins from these servers and generate an avatar of the head, as for online-mode servers (which get the head image from the Mojang profile API)

**Comment by dhghf** [comment]
I'm going to merge this in with issue #16
