### ISSUE TITLE
Minecraft Skin Head Overlay

### ISSUE THREAD

**Issue by dhghf** [dhghf/marco#5]
Currently in Minecraft there can be two layers to a player's head. Our approach of setting the Matrix profile picture only crops out their face and scales it to 200x200, it would be finished if we also grabbed the second layer of the face. The issue is that not all skins have a second layer, they all have the same PNG image resolution but where the second layer should be can either be fully black or transparent which tells the Minecraft server there is no second layer to the face. 

tl;dr psuedo code:
1. Crop face out of skin
2. Crop second layer face out of skin
3. See if the second layer isn't 100% black or transparent
4. If there is a second layer then put it on top of the face and return the buffer
5. else return the face buffer without the second layer.

Skin Examples:
 - My skin (does have second layer): http://textures.minecraft.net/texture/1671ca57b79f1e0c7f661941546249aba4efba584870453c1fb1a8a74cb20bbb
 - Notch's skin (does NOT have second layer): http://textures.minecraft.net/texture/292009a4925b58f02c77dadc3ecef07ea4c7472f64e0fdc32ce5522489362680

**Comment by dali99** [comment]
Using https://crafatar.com/ this is really easy.

This would also add the option of adding a 3d render setting _very_ easilly

**Comment by techkid6** [comment]
The "overlay" can also be entirely white, as with the skin of the player SlowRiot: http://textures.minecraft.net/texture/97431882a05515b9496ac0df5774e47edbbb1212af99368daf8f1d5afec8975b

**Comment by dhghf** [comment]
You're right, this also applies to default skins

**Comment by dhghf** [comment]
This issue is going to be discarded for more appropriate approach which is @dali99's 3D rendering technique
